app = 'on-time'
primary_region = 'ams'

[build]

[env]
  TZ = "America/Toronto"

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "app_data"
  destination = "/data"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
[env]
  TZ = "America/Toronto"
